;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		c-electric-delete-forward
		ibus-handle-event
		kill-region
		set-buffer-file-coding-system
		))

(setq mc/cmds-to-run-once
      '(
		))
