(add-to-list 'load-path "~/.emacs.d/elisp/expand-region/")
(require 'expand-region)
(global-set-key (kbd "C-,") 'er/expand-region)
(global-set-key (kbd "C-M-,") 'er/contract-region)
(transient-mark-mode t)
