; zencoding
(require 'emmet-mode)
(add-hook 'sgml-mode-hook 'emmet-mode)
(add-hook 'css-mode-hook  'emmet-mode)
(add-hook 'emmet-mode-hook (lambda ()
							 (setq emmet-indentation 2)
							 (define-key emmet-mode-keymap (kbd "C-j") nil)
							 (define-key emmet-mode-keymap (kbd "<C-return>") nil)
							 (define-key emmet-mode-keymap (kbd "M-j") 'emmet-expand-line)
							 ))
(setq emmet-move-cursor-between-quotes t)
(setq emmet-preview-default nil)

; js
(autoload 'js2-mode "js2-mode" nil t)
(add-to-list 'auto-mode-alist '("\\.js$" . js2-mode))
(add-to-list 'auto-mode-alist '("\\.json$" . js2-mode))
(defun my-js2-mode-hook()
  (gtags-mode 1))
(add-hook 'js2-mode-hook 'my-js2-mode-hook)
